<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://mgt.pingReceiver.carbon.wso2.org" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns1="http://org.apache.axis2/xsd" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="http://mgt.pingReceiver.carbon.wso2.org">
   <wsdl:documentation>PingManager</wsdl:documentation>
   <wsdl:types>
      <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://mgt.pingReceiver.carbon.wso2.org">
         <xs:element name="getMESSAGE">
            <xs:complexType>
               <xs:sequence/>
            </xs:complexType>
         </xs:element>
         <xs:element name="getMESSAGEResponse">
            <xs:complexType>
               <xs:sequence>
                  <xs:element minOccurs="0" name="return" nillable="true" type="xs:string"/>
               </xs:sequence>
            </xs:complexType>
         </xs:element>
      </xs:schema>
   </wsdl:types>
   <wsdl:message name="getMESSAGERequest">
      <wsdl:part name="parameters" element="ns:getMESSAGE"/>
   </wsdl:message>
   <wsdl:message name="getMESSAGEResponse">
      <wsdl:part name="parameters" element="ns:getMESSAGEResponse"/>
   </wsdl:message>
   <wsdl:portType name="PingManagerPortType">
      <wsdl:operation name="getMESSAGE">
         <wsdl:input message="ns:getMESSAGERequest" wsaw:Action="urn:getMESSAGE"/>
         <wsdl:output message="ns:getMESSAGEResponse" wsaw:Action="urn:getMESSAGEResponse"/>
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:binding name="PingManagerSoap11Binding" type="ns:PingManagerPortType">
      <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
      <wsdl:operation name="getMESSAGE">
         <soap:operation soapAction="urn:getMESSAGE" style="document"/>
         <wsdl:input>
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output>
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:binding name="PingManagerSoap12Binding" type="ns:PingManagerPortType">
      <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
      <wsdl:operation name="getMESSAGE">
         <soap12:operation soapAction="urn:getMESSAGE" style="document"/>
         <wsdl:input>
            <soap12:body use="literal"/>
         </wsdl:input>
         <wsdl:output>
            <soap12:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:binding name="PingManagerHttpBinding" type="ns:PingManagerPortType">
      <http:binding verb="POST"/>
      <wsdl:operation name="getMESSAGE">
         <http:operation location="getMESSAGE"/>
         <wsdl:input>
            <mime:content type="text/xml" part="parameters"/>
         </wsdl:input>
         <wsdl:output>
            <mime:content type="text/xml" part="parameters"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="PingManager">
      <wsdl:port name="PingManagerHttpsSoap11Endpoint" binding="ns:PingManagerSoap11Binding">
         <soap:address location="https://DESKTOP-Q90AKCD:8243/services/PingManager.PingManagerHttpsSoap11Endpoint"/>
      </wsdl:port>
      <wsdl:port name="PingManagerHttpsSoap12Endpoint" binding="ns:PingManagerSoap12Binding">
         <soap12:address location="https://DESKTOP-Q90AKCD:8243/services/PingManager.PingManagerHttpsSoap12Endpoint"/>
      </wsdl:port>
      <wsdl:port name="PingManagerHttpsEndpoint" binding="ns:PingManagerHttpBinding">
         <http:address location="https://DESKTOP-Q90AKCD:8243/services/PingManager.PingManagerHttpsEndpoint"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>